version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: java-demo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: java-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - java-demo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: java-demo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@javademo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
    networks:
      - java-demo-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  java-demo-network:

configs:
  pgadmin_servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "java-demo",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "java-demo",
            "Username": "postgres",
            "SSLMode": "prefer"
          }
        }
      }
